In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [75]:

# Load the FIFA 21 dataset and disable low_memory warnings
df = pd.read_csv("C:/Users/hp/Downloads/DataCleaning/Data/fifa21_raw_data.csv", low_memory=False)

# Display the first five rows of the dataset
df.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [76]:
# Display the Height and Weight columns
df[["Height", "Weight"]]

# Check the datatypes of Height and Weight columns
df[["Height", "Weight"]].dtypes

# OR (more detailed info)
df[["Height", "Weight"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  18979 non-null  object
 1   Weight  18979 non-null  object
dtypes: object(2)
memory usage: 296.7+ KB

In [77]:
# Split feet and inches easily
df["Feet"] = df["Height"].str.split("'").str[0].astype(float)
df["Inch"] = df["Height"].str.split("'").str[1].str.replace('"', '').astype(float)
# Convert to cm
df["Height"] = df["Feet"] * 30.48 + df["Inch"] * 2.54
#convert "lbs" to "kg"
df["Weight"] = df["Weight"].str.replace("lbs", "").astype(float) * 0.453592

In [78]:
#Display Height & Weight as cm & kg
df[["Height","Weight"]]

       Height     Weight
0      170.18  72.121128
1      187.96  83.007336
2      187.96  87.089664
3      180.34  69.853168
4      175.26  68.038800
...       ...        ...
18974  177.80  69.853168
18975  170.18  58.059776
18976  177.80  66.224432
18977  175.26  64.863656
18978  175.26  68.038800

[18979 rows x 2 columns]

In [79]:
df.columns

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight',
       'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Feet', 'Inch'],
      dtype='object')

In [80]:
# Convert Joined column into datetime format
df["Joined"] = pd.to_datetime(df["Joined"])

# Split into year, month, day
df["Joined_Year"] = df["Joined"].dt.year
df["Joined_Month"] = df["Joined"].dt.month
df["Joined_Day"] = df["Joined"].dt.day

# Show results
df[["Joined", "Joined_Year", "Joined_Month", "Joined_Day"]].head()

      Joined  Joined_Year  Joined_Month  Joined_Day
0 2004-07-01         2004             7           1
1 2018-07-10         2018             7          10
2 2014-07-16         2014             7          16
3 2015-08-30         2015             8          30
4 2017-08-03         2017             8           3

In [81]:
df[["Value","Wage","Release Clause"]]

        Value   Wage Release Clause
0      €67.5M  €560K        €138.4M
1        €46M  €220K         €75.9M
2        €75M  €125K        €159.4M
3        €87M  €370K          €161M
4        €90M  €270K        €166.5M
...       ...    ...            ...
18974    €35K    €1K           €57K
18975    €60K   €500          €165K
18976    €40K    €1K           €70K
18977    €60K   €500          €165K
18978    €60K   €500          €167K

[18979 rows x 3 columns]

In [82]:
import numpy as np

# Remove € sign
df["Value"] = df["Value"].str.replace("€", "", regex=False)
df["Wage"] = df["Wage"].str.replace("€", "", regex=False)
df["Release Clause"] = df["Release Clause"].str.replace("€", "", regex=False)

# Replace missing or non-numeric entries with NaN
df["Value"] = df["Value"].replace(["-", "--", "Free", ""], np.nan)
df["Wage"] = df["Wage"].replace(["-", "--", "Free", ""], np.nan)
df["Release Clause"] = df["Release Clause"].replace(["-", "--", "Free", ""], np.nan)

# --- VALUE ---
df.loc[df["Value"].str.contains("M", na=False), "Value"] = (
    df.loc[df["Value"].str.contains("M", na=False), "Value"]
      .str.replace("M", "", regex=False).astype(float) * 1_000_000
)

df.loc[df["Value"].str.contains("K", na=False), "Value"] = (
    df.loc[df["Value"].str.contains("K", na=False), "Value"]
      .str.replace("K", "", regex=False).astype(float) * 1_000
)

# --- WAGE ---
df.loc[df["Wage"].str.contains("M", na=False), "Wage"] = (
    df.loc[df["Wage"].str.contains("M", na=False), "Wage"]
      .str.replace("M", "", regex=False).astype(float) * 1_000_000
)

df.loc[df["Wage"].str.contains("K", na=False), "Wage"] = (
    df.loc[df["Wage"].str.contains("K", na=False), "Wage"]
      .str.replace("K", "", regex=False).astype(float) * 1_000
)

# --- RELEASE CLAUSE ---
df.loc[df["Release Clause"].str.contains("M", na=False), "Release Clause"] = (
    df.loc[df["Release Clause"].str.contains("M", na=False), "Release Clause"]
      .str.replace("M", "", regex=False).astype(float) * 1_000_000
)

df.loc[df["Release Clause"].str.contains("K", na=False), "Release Clause"] = (
    df.loc[df["Release Clause"].str.contains("K", na=False), "Release Clause"]
      .str.replace("K", "", regex=False).astype(float) * 1_000
)

# Final convert to integers
df["Value"] = df["Value"].astype(float).astype(int)
df["Wage"] = df["Wage"].astype(float).astype(int)
df["Release Clause"] = df["Release Clause"].astype(float).astype(int)

In [83]:
# Display the Value, Wage, and Release Clause columns
df[["Value", "Wage", "Release Clause"]].head()

      Value    Wage  Release Clause
0  67500000  560000       138400000
1  46000000  220000        75900000
2  75000000  125000       159400000
3  87000000  370000       161000000
4  90000000  270000       166500000

In [84]:
# Show detailed information (dtype, non-null counts, memory usage)
# for the Value, Wage, and Release Clause columns
df[["Value", "Wage", "Release Clause"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Value           18979 non-null  int64
 1   Wage            18979 non-null  int64
 2   Release Clause  18979 non-null  int64
dtypes: int64(3)
memory usage: 444.9 KB

In [85]:
# Remove newline characters (\n) and extra spaces from the Hits column
df["Hits"] = df["Hits"].str.replace("\n", "", regex=False).str.strip()
# Display cleaned Hits column
df["Hits"].head()

0    372
1    344
2     86
3    163
4    273
Name: Hits, dtype: object

In [86]:
df[["Team & Contract"]]

                                         Team & Contract
0                  \n\n\n\nFC Barcelona\n2004 ~ 2021\n\n
1                      \n\n\n\nJuventus\n2018 ~ 2022\n\n
2               \n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n
3               \n\n\n\nManchester City\n2015 ~ 2023\n\n
4           \n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n
...                                                  ...
18974  \n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...
18975           \n\n\n\nOldham Athletic\n2020 ~ 2021\n\n
18976                \n\n\n\nWuhan Zall\n2018 ~ 2022\n\n
18977           \n\n\n\nOldham Athletic\n2020 ~ 2021\n\n
18978              \n\n\n\nClub Bolívar\n2020 ~ 2024\n\n

[18979 rows x 1 columns]

In [87]:
# Step 1: Remove newline characters and extra spaces
df["Team & Contract"] = df["Team & Contract"].str.replace("\n", " ", regex=False).str.strip()

# Step 2: Replace multiple spaces with a single space
df["Team & Contract"] = df["Team & Contract"].replace(r"\s+", " ", regex=True)

# Step 3: Split into Team (text part) and Contract (year range)
# We split on the first occurrence of a digit (start of "2004")
df["Team"] = df["Team & Contract"].str.extract(r"([A-Za-z\s\.]+)")
df["Contract"] = df["Team & Contract"].str.extract(r"(\d{4}.*)")

# Step 4: Clean Team & Contract fields
df["Team"] = df["Team"].str.strip()
df["Contract"] = df["Contract"].str.strip()

In [72]:
df[["Team","Contract"]]

                                      Team     Contract
0                             FC Barcelona  2004 ~ 2021
1                                 Juventus  2018 ~ 2022
2                                      Atl  2014 ~ 2023
3                          Manchester City  2015 ~ 2023
4                              Paris Saint  2017 ~ 2022
...                                    ...          ...
18974  Chongqing Dangdai Lifan FC SWM Team  2020 ~ 2020
18975                      Oldham Athletic  2020 ~ 2021
18976                           Wuhan Zall  2018 ~ 2022
18977                      Oldham Athletic  2020 ~ 2021
18978                             Club Bol  2020 ~ 2024

[18979 rows x 2 columns]